[package]
name = "update"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow   = "1.0.98"
clap     = { version = "4.5.39", features = ["derive"] }
dirs     = "5"
reqwest  = { version = "0.12.18", features = ["blocking", "rustls-tls"] }